DWAPlannerROS:
# Robot Configuration Parameters, detail from http://wiki.ros.org/dwa_local_planner?distro=kinetic
# a sample from https://github.com/ros-planning/navigation_tutorials/blob/indigo-devel/navigation_stage/move_base_config/dwa_local_planner_params.yaml
  max_vel_x: 0.9
  min_vel_x: 0.1
  max_vel_y: 0.0  # diff drive robot
  min_vel_y: 0.0  # diff drive robot
  max_trans_vel: 0.8 # choose slightly less than the base's capability
  min_trans_vel: 0.25  # min trans velocity when there is negligible rotational velocity, Notice higher than 0.4 does not work on the simulator
  trans_stopped_vel: 0.1
  # Warning! do not set min_trans_vel to 0.0 otherwise dwa will always think translational velocities
  #   are non-negligible and small in place rotational velocities will be created.
  max_rot_vel: 1.0  # choose slightly less than the base's capability
  min_rot_vel: 0.2  # 2.9 this is the min angular velocity when there is negligible translational velocity
  rot_stopped_vel: 0.1
  acc_lim_x: 1.2 # maximum is theoretically 2.0
  acc_lim_theta: 1.2
  acc_lim_y: 0.0      # diff drive robot
# Goal Tolerance Parameters
  yaw_goal_tolerance: 3.14  # discard orientation
  xy_goal_tolerance: 0.4
  latch_xy_goal_tolerance: false
# Forward Simulation Parameters
  sim_time: 1.7       # 1.7 original 1.0 https://github.com/ros-planning/navigation/issues/147
  vx_samples: 8       # 3
  vy_samples: 1       # diff drive robot, there is only one sample
  vtheta_samples: 20  # 20

TrajectoryPlannerROS:
  holonomic_robot: false

  acc_lim_x: 1.0
  acc_lim_theta: 2.5
  min_vel_theta: -0.9
  max_vel_theta: 0.9

  max_vel_x: 0.6
  min_vel_x: 0.1
  
  escape_vel: -0.3
  
  # Forward Simulation Parameters
  sim_time: 1.7
  sim_granularity: 0.1
  angular_sim_granularity: 0.1
  vx_samples: 6
  vtheta_samples: 10

  # Trajectory scoring parameters
  meter_scoring: true # assume that goal_distance and path_distance are expressed in units of meters
  occdist_scale: 0.1 # The weighting for how much the controller should attempt to avoid obstacles. default 0.01
  pdist_scale: 0.7 # The weighting for how much the controller should stay close to the path it was given . default 0.6
  gdist_scale: 0.7 # The weighting for how much the controller should attempt to reach its local goal, also controls speed  default 0.8

  # Oscillation Prevention Parameters
  escape_reset_dist: 0.1
  escape_reset_theta: 0.3
  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 3.14

